intents:

  - name: yield_history
    examples:
      en:
        - "What was last year’s rice yield?"
        - "Tell me my paddy production for last year."
        - "How much maize did I produce last season?"
        - "Give me my yield history for wheat."
        - "Last year, how much did I harvest?"
        - "Check last month’s crop production."
        - "Tell me the output of rice from last year."
        - "How much was my cotton yield last year?"
        - "Show me last season’s harvest report."
        - "What was my groundnut production last season?"
      hi:
        - "पिछले साल का धान उत्पादन कितना था?"
        - "मुझे पिछले साल की गेहूँ की पैदावार बताओ।"
        - "पिछले सीज़न में मक्का की कितनी पैदावार हुई?"
        - "धान की पैदावार पिछले साल कितनी थी?"
        - "मेरा पिछले साल का उत्पादन कितना था?"
        - "मुझे पिछले महीने का धान उत्पादन बताओ।"
        - "गेहूँ की पैदावार का इतिहास बताओ।"
        - "मेरी कपास की पैदावार पिछले साल कितनी हुई?"
        - "मुझे पिछले साल की फसल की रिपोर्ट दो।"
        - "मूँगफली का उत्पादन पिछले सीज़न में कितना था?"
      or:
        - "ଗତବର୍ଷ ଧାନ ଫଳନ କେତେ ହେଲା?"
        - "ଗତବର୍ଷ ଗହମ ଉତ୍ପାଦନ କେତେ ହୋଇଥିଲା?"
        - "ପିଛଲା ଋତୁରେ ମକାଇ ଉତ୍ପାଦନ କେତେ ହୋଇଥିଲା?"
        - "ଧାନ ଫଳନ ଗତବର୍ଷ କେତେ ଥିଲା?"
        - "ଗତବର୍ଷ ମୋର ଉତ୍ପାଦନ କେତେ ହୋଇଥିଲା?"
        - "ପିଛଲା ମାସରେ ଧାନ ଫଳନ କେତେ?"
        - "ଗହମ ଉତ୍ପାଦନ ଇତିହାସ କୁହ।"
        - "ଗତବର୍ଷ କପାସ ଉତ୍ପାଦନ କେତେ ହୋଇଥିଲା?"
        - "ମୋର ଫସଲ ରିପୋର୍ଟ କୁହ।"
        - "ପିଛଲା ଋତୁରେ ବଦାମ ଉତ୍ପାଦନ କେତେ ହେଲା?"

  - name: weather_info
    examples:
      en:
        - "What will the weather be tomorrow?"
        - "Tell me today’s forecast."
        - "Will it rain next week?"
        - "How is the weather today?"
        - "Give me the monsoon update."
        - "Is it sunny tomorrow?"
        - "What’s the temperature right now?"
        - "Will there be a storm this week?"
        - "Check weather for next month."
        - "How will the weather be this season?"
      hi:
        - "कल का मौसम कैसा होगा?"
        - "आज का मौसम कैसा है?"
        - "क्या अगले हफ्ते बारिश होगी?"
        - "मुझे आज का मौसम बताओ।"
        - "मॉनसून की जानकारी दो।"
        - "क्या कल धूप होगी?"
        - "अभी का तापमान कितना है?"
        - "क्या इस हफ्ते तूफान आएगा?"
        - "अगले महीने का मौसम कैसा होगा?"
        - "इस सीज़न में मौसम कैसा रहेगा?"
      or:
        - "ଆସନ୍ତାକାଲି ଆବହାଓଆ କେମିତି ରହିବ?"
        - "ଆଜିର ଆବହାଓଆ କେମିତି?"
        - "ଆଗାମୀ ସପ୍ତାହେ ବର୍ଷା ହେବ କି?"
        - "ଆଜିର ଆବହାଓଆ କୁହ।"
        - "ବର୍ଷା ଋତୁ ସୂଚନା ଦିଅ।"
        - "ଆସନ୍ତାକାଲି ଧୂପ ରହିବ କି?"
        - "ବର୍ତ୍ତମାନ ତାପମାତ୍ରା କେତେ?"
        - "ଏହି ସପ୍ତାହେ ଝଡ଼ ହେବ କି?"
        - "ଆଗାମୀ ମାସରେ ଆବହାଓଆ କେମିତି?"
        - "ଏହି ଋତୁରେ ଆବହାଓଆ କେମିତି ରହିବ?"

  - name: sowing_advice
    examples:
      en:
        - "When should I sow rice this year?"
        - "What is the best time for maize planting?"
        - "Suggest sowing dates for wheat."
        - "When should I plant cotton?"
        - "What is the right season for groundnut?"
        - "Guide me on sowing paddy."
        - "Which month is good for sowing maize?"
        - "Tell me the sowing advice for my crops."
        - "Is now the right time for sowing?"
        - "What season is good for planting vegetables?"
      hi:
        - "धान बोने का सही समय कब है?"
        - "मक्का की बुवाई कब करनी चाहिए?"
        - "गेहूँ की बुवाई की तारीख बताओ।"
        - "कपास की बुवाई कब करनी चाहिए?"
        - "मूँगफली के लिए सही मौसम कौन सा है?"
        - "धान बोने का मार्गदर्शन करो।"
        - "मक्का की बुवाई के लिए कौन सा महीना सही है?"
        - "मेरी फसल की बुवाई सलाह बताओ।"
        - "क्या अभी बुवाई का सही समय है?"
        - "सब्जियों की बुवाई का मौसम कौन सा है?"
      or:
        - "ଏହି ବର୍ଷ ଧାନ କେବେ ପ୍ରତିରୋପଣ କରିବି?"
        - "ମକାଇ ପ୍ରତିରୋପଣ ପାଇଁ ସର୍ବୋତ୍ତମ ସମୟ କଣ?"
        - "ଗହମ ପ୍ରତିରୋପଣ ତାରିଖ କୁହ।"
        - "କପାସ କେବେ ପ୍ରତିରୋପଣ କରିବା?"
        - "ବଦାମ ପାଇଁ ଠିକ୍ ସମୟ କଣ?"
        - "ଧାନ ପ୍ରତିରୋପଣ ପାଇଁ ସଲାହ ଦିଅ।"
        - "ମକାଇ ପାଇଁ କେଉଁ ମାସ ସଠିକ?"
        - "ମୋର ଫସଲ ପ୍ରତିରୋପଣ ସଲାହ କୁହ।"
        - "ଏବେ ପ୍ରତିରୋପଣ ପାଇଁ ଠିକ୍ ସମୟ କି?"
        - "ସବ୍ଜି ପ୍ରତିରୋପଣ ପାଇଁ କେଉଁ ଋତୁ ଭଲ?"

  - name: govt_scheme_info
    examples:
      en:
        - "Tell me about government subsidies."
        - "What are the schemes for farmers this year?"
        - "Is there any loan scheme for crops?"
        - "What is PM-Kisan about?"
        - "Tell me about fertilizer subsidy."
        - "Are there any insurance schemes for paddy?"
        - "What support is available for wheat farmers?"
        - "Give me government scheme details."
        - "Which schemes can help me as a farmer?"
        - "Is there any subsidy on seeds?"
      hi:
        - "सरकारी सब्सिडी के बारे में बताओ।"
        - "किसानों के लिए इस साल की योजनाएँ क्या हैं?"
        - "क्या फसलों के लिए कोई लोन योजना है?"
        - "पीएम-किसान योजना क्या है?"
        - "उर्वरक सब्सिडी की जानकारी दो।"
        - "क्या धान के लिए कोई बीमा योजना है?"
        - "गेहूँ किसानों के लिए क्या सहायता है?"
        - "मुझे सरकारी योजनाओं की जानकारी दो।"
        - "किसानों के लिए कौन-कौन सी योजनाएँ उपलब्ध हैं?"
        - "क्या बीज पर कोई सब्सिडी है?"
      or:
        - "ସରକାରୀ ସହାୟତା ବିଷୟରେ କୁହ।"
        - "ଏହି ବର୍ଷ କୃଷକ ପାଇଁ କଣ କଣ ଯୋଜନା ଅଛି?"
        - "ଫସଲ ପାଇଁ କୌଣସି ଋଣ ଯୋଜନା ଅଛି କି?"
        - "ପିଏମ-କିସାନ ଯୋଜନା କଣ?"
        - "ସରକାରୀ ରାସାୟନିକ ସହାୟତା ବିଷୟରେ କୁହ।"
        - "ଧାନ ପାଇଁ କୌଣସି ବୀମା ଯୋଜନା ଅଛି କି?"
        - "ଗହମ କୃଷକଙ୍କ ପାଇଁ କଣ ସହାୟତା ଅଛି?"
        - "ମୋତେ ସରକାରୀ ଯୋଜନାର ସୂଚନା ଦିଅ।"
        - "କୃଷକଙ୍କ ପାଇଁ କେଉଁ ଯୋଜନା ଉପଲବ୍ଧ?"
        - "ବିଆ ପାଇଁ କୌଣସି ସହାୟତା ଅଛି କି?"
